baseURL = "github.com/cartershi/blog/"
#baseURL = "cartershi.github.io/blog/"
languageCode = "en-us"
title = "syx的日志"
canonifyurls = true
paginate = 10
theme = "hyde"
publishDir = "docs"

[params]
	author = "Shi Yuxuan"
	description = "洗澡王"	
    license = "CC BY-SA 4.0"
    licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
    showBuiltWith = true

    # https://highlightjs.org
    highlightjs = true
    highlightjsstyle = "github"
	themeColor = "theme-base-08"

[taxonomies]
  tag = "tags"
  series = "series"
  category = "categories"
  
[params.social]
	github = "catershi"
	
[indexes]
  tag = "tags"
  topic = "topics"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/post/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 300
    url = "/about/"
[[menu.main]]
    name = "Tags"
    identifier = "tags"
    weight = 400
    url = "/tags/"